INSERT INTO orders (customer_name, order_date) VALUES ('Jon Snow', '2025-01-01');
INSERT INTO orders (customer_name, order_date) VALUES ('Daenerys Targaryen', '2025-01-02');
INSERT INTO orders (customer_name, order_date) VALUES ('Arya Stark', '2025-01-03');
INSERT INTO orders (customer_name, order_date) VALUES ('Tyrion Lannister', '2025-01-04');
INSERT INTO orders (customer_name, order_date) VALUES ('Cersei Lannister', '2025-01-05');
INSERT INTO orders (customer_name, order_date) VALUES ('Bran Stark', '2025-01-06');
INSERT INTO orders (customer_name, order_date) VALUES ('Sansa Stark', '2025-01-07');
INSERT INTO orders (customer_name, order_date) VALUES ('Jaime Lannister', '2025-01-08');
INSERT INTO orders (customer_name, order_date) VALUES ('Sandor Clegane', '2025-01-09');
INSERT INTO orders (customer_name, order_date) VALUES ('Brienne of Tarth', '2025-01-10');
