INSERT INTO products (name, price) VALUES ('Intel Core i7 Processor', 320.0);
INSERT INTO products (name, price) VALUES ('AMD Ryzen 9 CPU', 450.0);
INSERT INTO products (name, price) VALUES ('NVIDIA RTX 3080 Graphics Card', 699.99);
INSERT INTO products (name, price) VALUES ('Corsair Vengeance 16GB RAM', 89.99);
INSERT INTO products (name, price) VALUES ('Samsung 1TB SSD', 119.99);
INSERT INTO products (name, price) VALUES ('Western Digital 2TB HDD', 79.99);
INSERT INTO products (name, price) VALUES ('Razer DeathAdder Gaming Mouse', 49.99);
INSERT INTO products (name, price) VALUES ('Logitech G Pro Keyboard', 129.99);
INSERT INTO products (name, price) VALUES ('Asus ROG Gaming Monitor', 399.99);
INSERT INTO products (name, price) VALUES ('HyperX Cloud II Gaming Headset', 99.99);
INSERT INTO products (name, price) VALUES ('Microsoft Office 365 License', 79.99);
INSERT INTO products (name, price) VALUES ('Adobe Photoshop Subscription', 239.99);
INSERT INTO products (name, price) VALUES ('Cyberpunk 2077 (PC Game)', 59.99);
INSERT INTO products (name, price) VALUES ('Call of Duty: Modern Warfare', 69.99);
INSERT INTO products (name, price) VALUES ('Minecraft (PC Game)', 29.99);
INSERT INTO products (name, price) VALUES ('Windows 11 Pro License', 199.99);
INSERT INTO products (name, price) VALUES ('MacBook Pro 14-inch', 1999.99);
INSERT INTO products (name, price) VALUES ('Dell XPS 13 Laptop', 1299.99);
INSERT INTO products (name, price) VALUES ('Alienware Aurora Gaming PC', 1499.99);
INSERT INTO products (name, price) VALUES ('Raspberry Pi 4 Model B', 55.0);
